# Generated by Django 6.0 on 2026-06-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('tiltle', models.CharField(max_length=100)),
                ('discribshen', models.TextField()),
            ],
        ),
    ]
