# Generated by Django 6.0 on 2026-07-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='shop/images', verbose_name='تصویر')),
                ('gheymat', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('category', models.CharField(choices=[('action', 'اکشن'), ('adventure', 'ماجراجویی'), ('openworld', 'جهان باز'), ('sport', 'ورزشی'), ('fight', 'مبارزه\u200cای'), ('horror', 'ترسناک'), ('race', 'مسابقه\u200cای')], default='action', max_length=20, verbose_name='سبک')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
