# Generated by Django 6.0 on 2026-07-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shop',
            table='game_shop_products',
        ),
    ]
